version: "3"

services:
  dj:
    build:
      context: ./
      dockerfile: Dockerfile
    container_name: dj
    command: gunicorn cortex.wsgi:application --bind 0.0.0.0:8000
    volumes:
      - data_media:/media
      - data_logs:/logs
      - data_emails:/emails
      - data_db:/db
    expose:
      - 8000
    env_file:
      - .env

  ng:
    container_name: ng
    image: nginx:1.19
    volumes:
      - ./static:/static
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf
    ports:
      - 80:80
    depends_on:
      - dj

  rabbitmq:
    container_name: rabbitmq
    image: rabbitmq:3-management
    environment:
      RABBITMQ_DEFAULT_USER: admin
      RABBITMQ_DEFAULT_PASS: adm1n
      RABBITMQ_DEFAULT_VHOST: /
    expose:
      - 5672
    ports:
      - '5672:5672'
#      - '15672:15672'

  celery-service:
    container_name: celery-service
    build: ./
    command: celery -A cortex worker -l info
    volumes:
      - "data_media:/media/"
      - "data_logs:/logs/"
      - "data_emails:/emails/"
    depends_on:
      - rabbitmq
    env_file:
      - .env

  celery-beat:
    container_name: celery-beat
    build: .
    command: celery -A cortex beat -l info --pidfile=
    volumes:
      - "data_media:/media/"
      - "data_logs:/logs/"
      - "data_emails:/emails/"
    depends_on:
      - rabbitmq
    env_file:
      - .env

volumes:
  data_media:
  data_logs:
  data_emails:
  data_db:
  nginx_data: