# Generated by Django 3.1 on 2020-08-30 18:32

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Moeda',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pais', models.CharField(max_length=50)),
                ('pais_codigo', models.SmallIntegerField()),
                ('sigla_swift', models.CharField(max_length=3)),
            ],
        ),
    ]
